root = "."
tmp_dir = "dist"

[build]
cmd = "go build -o ./dist/main"
bin = "dist/main"
full_bin = "APP_ENV=dev APP_USER=air ./dist/main"
include_ext = ["go", "tpl", "tmpl", "json", "sql", "yaml", "env"]
exclude_dir = ["tmp", "vendor", "build"]
include_dir = []
exclude_file = []
log = "app.log"
delay = 1000 # ms
stop_on_error = false
send_interrupt = false
kill_delay = 500 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true